on:
  push:
    branches:
      - 'main'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - id: build-publish
      uses: dijidiji/github-actions-react-to-ghp@main
